// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'mmappSlider': string;
  'mmappSlider-thumb': string;
  'mmappSlider-track': string;
}
export const cssExports: CssExports;
export default cssExports;
