// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controls': string;
  'flex': string;
  'icon': string;
  'left-controls': string;
  'middle-controls': string;
  'right-controls': string;
  'slider': string;
}
export const cssExports: CssExports;
export default cssExports;
