name: Build Package

on:
  push:
    branches-ignore:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Install and Build 🔧
      run: |
        yarn
        yarn build:all
